// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
namespace ML_NET_Training
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"User")]
            public float User { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Card")]
            public float Card { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Year")]
            public float Year { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Month")]
            public float Month { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Day")]
            public float Day { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Time")]
            public string Time { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Amount")]
            public string Amount { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Use Chip")]
            public string Use_Chip { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Merchant Name")]
            public float Merchant_Name { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Merchant City")]
            public string Merchant_City { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Merchant State")]
            public string Merchant_State { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Zip")]
            public float Zip { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"MCC")]
            public float MCC { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Is Fraud?")]
            public string Is_Fraud_ { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"User")]
            public float User { get; set; }

            [ColumnName(@"Card")]
            public float Card { get; set; }

            [ColumnName(@"Year")]
            public float Year { get; set; }

            [ColumnName(@"Month")]
            public float Month { get; set; }

            [ColumnName(@"Day")]
            public float Day { get; set; }

            [ColumnName(@"Time")]
            public float[] Time { get; set; }

            [ColumnName(@"Amount")]
            public float[] Amount { get; set; }

            [ColumnName(@"Use Chip")]
            public float[] Use_Chip { get; set; }

            [ColumnName(@"Merchant Name")]
            public float Merchant_Name { get; set; }

            [ColumnName(@"Merchant City")]
            public float[] Merchant_City { get; set; }

            [ColumnName(@"Merchant State")]
            public float[] Merchant_State { get; set; }

            [ColumnName(@"Zip")]
            public float Zip { get; set; }

            [ColumnName(@"MCC")]
            public float MCC { get; set; }

            [ColumnName(@"Is Fraud?")]
            public uint Is_Fraud_ { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.Join(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("Is Fraud?");
            if (labelColumn == null)
            {
                throw new Exception("Is Fraud? column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
